version: '3'

services:
    aptcacher:
        image: "yeticraft/docker-apt-cacher-ng:amd64"
        container_name: aptcacher
        restart: unless-stopped
        build: ./
        ports:
            - "3142:3142"
        volumes:
            - aptcacher-cache:/var/cache/apt-cacher-ng

volumes:
    aptcacher-cache:
